### ISSUE TITLE
Issue with html tag compliance

### ISSUE THREAD

**Issue by kapll** [sachet0/CPS530-Group-Project#1]
Anyways, um... I bought a whole bunch of shungite rocks, do you know what shungite is? Anybody know what shungite is? No, not Suge Knight, I think he's locked up in prison. I'm talkin' shungite. Anyways, it's a two billion year-old like, rock stone that protects against frequencies and unwanted frequencies that may be traveling in the air. That's my story, I bought a whole bunch of stuff. Put 'em around the la casa. Little pyramids, stuff like that.

**Comment by sachet0** [comment]
OOPSIE WOOPSIE!! 😳 Uwu 😚 We make a fucky wucky!! 🙅‍♂️🤷🏼‍♀️ A wittle fucko boingo! 🌈💫 The code monkeys 🙈🙉at our headquarters 🕍 💤 are working VEWY HAWD 💸💯 to fix this! ♿️

**Comment by kapll** [comment]
Excuse me Devin this didn't solve my problem
